<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
            <li class="nav-item" <?php if($page->isActive()) echo 'class="nav-item active"'?> role="presentation">
                <a class="nav-link" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php else: ?>
            <li class="nav-item dropdown <?php if($page->isActive()) echo 'active'; ?>">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <?php foreach($page->getPages() as $child): ?>
                        <a class="dropdown-item" href="<?php echo $child->getHref() ?>">
                            <?php echo $this->translate($child->getLabel()) ?>
                        </a>
                    <?php endforeach ?>
                </div>
            </li>
        <?php endif; ?>
        <?php $count++ ?>
    <?php endforeach; ?>
</ul>
